language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/linear_regression/code/linear_regression.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* codes/2-basics_in_machine_learning/linear_svm/code/linear_SVM.py test


after_success:
  coveralls

sudo: enabled
dist: trusty
